export const INITIALIZE_DATA = 'INITIALIZE_DATA';

export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';

export const GET_CURRENT_LOCATION_DETAILS_SUCCESS =
  'GET_CURRENT_LOCATION_DETAILS_SUCCESS';
export const GET_CURRENT_LOCATION_DETAILS_ERROR =
  'GET_CURRENT_LOCATION_DETAILS_ERROR';
